# Confluence pages to sync for this project.
#
# Each page entry has:
#   name:        Friendly name used with --page flag
#   url:         Full Confluence page URL (page ID is extracted automatically)
#
# Optional:
#   access:      "read-only" (default) or "read-write"
#   sync_children: true (default) or false
#   sync_attachments: true (default) or false
#   local_path:  Override where to store the markdown (default: confluence/<name>.md)
#
# Example:
#   pages:
#     - name: architecture
#       url: "https://your-domain.atlassian.net/wiki/spaces/TEAM/pages/12345678/Architecture"

pages: []
